name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'
env:
  GITHUB_USER: "${{secrets.USERNAME}}"
  GITHUB_EMAIL: "${{secrets.EMAIL}}"
  GITHUB_TOKEN: "${{secrets.API_TOKEN_GITHUB}}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set timezone to UTC+8
      run: |
        sudo rm -f /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        echo "$(date "+%Y.%m.%d %H:%M:%S UTC%z")" | tee /tmp/start_time
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y axel flex bison ncurses-dev texinfo gcc make libtool bc autoconf build-essential pkg-config tar lzip git autopoint gettext help2man txt2man libssl-dev wget
    - name: Create directory
      run: |
        mkdir -vp source output wget build/build-gcc

    # 下面是turbo-charge项目相关的步骤

    # 克隆turbo-charge存储库到source目录中，如果已经存在则更新到最新版本。
    - name: Clone turbo-charge repository
      run: |
        git clone https://github.com/shenming34/turbo-charge.git source/turbo-charge || (cd source/turbo-charge && git pull)

    # 编译turbo-charge
    - name: Compile turbo-charge
      run: |
        cd source/turbo-charge
        make

    # 将编译结果复制到output目录中
    - name: Copy files to output directory
      run: |
        cp -r source/turbo-charge/output/* output/

    # 提交编译结果到GitHub仓库
    - name: Push changes to GitHub repository
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
        git add output/
        git commit -m "Add compiled files"
        git push origin HEAD:${{ github.ref }}
